### ISSUE TITLE
感谢分享！有点小缺憾

### ISSUE THREAD

**Issue by xray1111** [JinpengLI/deep_ocr#1]
如果能将用caffe训练的过程写个简单的说明就好了！

**Comment by JinpengLI** [comment]
http://chongdata.com/articles 有一些教程，希望复合你要求。迟一些会推出一些线上的深度学习物理GPU主机给大家测试。

**Comment by JinpengLI** [comment]
我把这个issue关闭，因为在虫数据的网站已经有教程，欢迎继续提问。
