### ISSUE TITLE
after "cat deep_ocr_workspace.z* > unsplit_deep_ocr_workspace.zip" this command my ubuntu go die

### ISSUE THREAD

**Issue by Jayhello** [JinpengLI/deep_ocr#11]
after "cat deep_ocr_workspace.z* > unsplit_deep_ocr_workspace.zip" this command my ubuntu go die
mybe the file is too big

**Comment by JinpengLI** [comment]
It works on my machine. Could you please post error message? Thanks in advance.

**Comment by Jayhello** [comment]
后来好了，请问我添加自己的图片测试，这么测试啊。发现 docker里面添加图片，没有加载进去啊。你的docker可以配置为ubuntu 普通用户添加运行吗？然后添加自己的测试图片

**Comment by JinpengLI** [comment]
首先声明一点，通用的ocr接口还是没有弄好，关于添加自己的图片进去，可以考虑添加到解压后的workspace里面，这样就可以在docker container里面的/workspace出现

还有其他方法，下面是如何拷贝文件进去container：

http://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container

**Comment by JinpengLI** [comment]
主机内存问题，跟项目关系不大。
