### ISSUE TITLE
使用docker怎么添加自己的图片测试啊

### ISSUE THREAD

**Issue by Jayhello** [JinpengLI/deep_ocr#12]
使用docker怎么添加自己的图片测试啊，感觉添加起来好麻烦啊

**Comment by JinpengLI** [comment]
首先声明一点，通用的ocr接口还是没有弄好，还是需要自己做文字分割，关于添加自己的图片进去，可以考虑添加到解压后的workspace里面，这样就可以在docker container里面的/workspace出现

还有其他方法，下面是如何拷贝文件进去container：

http://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container

**Comment by Jayhello** [comment]
可以留个联系方式吗（QQ或者微信）？我做传统的opencv+OCR图片文字的识别效果不好（图片背景较为复杂），现在想看下深度学习怎么样？

**Comment by JinpengLI** [comment]
不太想做太多客服工作。。我要上班工作写程序。。不留了。。不好意思，请理解

**Comment by JinpengLI** [comment]
这个属于docker使用问题，跟这个项目关系不大，所以关闭这个issue

**Comment by Jayhello** [comment]
好滴，谢谢哈
