### ISSUE TITLE
训练样本是怎么取得的

### ISSUE THREAD

**Issue by xupeng082008** [JinpengLI/deep_ocr#14]
您好，请问您的训练样本容量是多大的，然后训练样本是如何获得的？

**Comment by JinpengLI** [comment]
印象中生成5000个字左右，忘记具体多少了，具体如何生存训练数据见 #7

**Comment by xupeng082008** [comment]
万分感谢您的回复，谢谢！谢谢！
我主攻方向是深度学习，在做中文汉字一二级识别（7000多类），您对深度学习或者说计算机视觉学习，作为资深研究学者，可以给出一些建议嘛？谢谢
