### ISSUE TITLE
你好~请问windows下可以运行deep_ocr吗

### ISSUE THREAD

**Issue by i-Tree** [JinpengLI/deep_ocr#21]
请问windows下可以运行deep_ocr吗，能不能用python调用，还是只能使用命令行运行。
另：之前没有使用过docker，从docker官网下载windows稳定版时无法安装。百度云上下载两个文件的速度很慢。不知有没有方法可以解决。

**Comment by JinpengLI** [comment]
你可以看看Dockerfile是怎样写，然年看看windows下面怎么弄，我没有太多能力一个人维护那么多平台，不好意思。

**Comment by i-Tree** [comment]
没事没事，感觉已经很厉害了。谢谢
