### ISSUE TITLE
docker error,how to use without docker

### ISSUE THREAD

**Issue by Jayhello** [JinpengLI/deep_ocr#4]
1.  you don't  give you env  like  opencv2.4 or 3.0  python2.7 or python3.0
2. how to use without docker

**Comment by JinpengLI** [comment]
Hi,

Thanks for your feedback. As I said, to reduce the installation complexity, I propose the docker.

In fact, you can check out the installation steps from Dockerfile (https://github.com/JinpengLI/deep_ocr_cpu_docker/blob/master/Dockerfile)

```
FROM ubuntu:14.04
MAINTAINER mr.li.jinpeng@gmail.com

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        wget \
        libatlas-base-dev \
        libboost-all-dev \
        libgflags-dev \
...

``` 

Once you have finished the installation, you can start to use deep_ocr.
