### ISSUE TITLE
error  你的百度云没有更新出了错误y_tag_json只有ABC啊

### ISSUE THREAD

**Issue by Jayhello** [JinpengLI/deep_ocr#5]
1.  File "/opt/deep_ocr/reco_chars.py", line 53, in _predict_cv2_imgs_sub
    item = (self.y_tag_json[str(index)],
KeyError: '4528'
2.还有就是拿个只有abc这样的jpc  
ocr res:
什么都没有啊

**Comment by JinpengLI** [comment]
能否列出百度云解压后的文件里面所有文件结构? (注意有两个解压包，放在同一个目录解压。)

ubuntu下面解压目录下可以运行

```
tree
```

获取文件夹结构。刚刚测试了一下，能用。

**Comment by JinpengLI** [comment]
刚刚测试了一下，重新上传两个压缩文件，现在应该可以用
