### ISSUE TITLE
博客代码

### ISSUE THREAD

**Issue by shartoo** [JinpengLI/deep_ocr#6]
您好！你的博客代码非常优雅简洁，可否fork你的博客代码？GitHub上好像没有看到。

**Comment by JinpengLI** [comment]
不清楚你指的博客代码是具体那些?

不过这里有一些课程代码

```
https://github.com/JinpengLI/deep_ocr/tree/master/lessons
```

**Comment by shartoo** [comment]
@JinpengLI  你们的教程系列的 [教程](http://chongdata.com/articles/) http://chongdata.com/articles/ ，如果是开放的话，是否可以分享？

**Comment by JinpengLI** [comment]
其实就是wordpress，都是开源的啊? 我理解错了?

**Comment by JinpengLI** [comment]
由于问题跟这个项目关系不大，所以关闭这个issue，博客本身是wordpress，wordpress是开源的
