### ISSUE TITLE
关于文字转图片的问题

### ISSUE THREAD

**Issue by chibai** [JinpengLI/deep_ocr#7]
我上次问过，您没有回答清楚啊~
我没看出来你拿到身份证字体格式后，如何遍历下所有文字形成图片？？
你能说得清楚些吗
如何从文字转到图片？？

**Comment by JinpengLI** [comment]
其实在

```
http://chongdata.com/articles/?p=253
```

有介绍(但是没有介绍身份证有哪些字体，关于身份证需要哪些字体可以网上查查)。其中

```
deep_ocr_make_caffe_dataset --out_caffe_dir /workspace/caffe_dataset_lower_eng \
            --font_dir /opt/deep_ocr/data/fonts/chinese_fonts \
            --width 28 --height 28 --margin 4 --langs lower_eng
```

输出图片。其中lower_eng是输出的字符集合, 其中lower_eng是输出的字符集合，具体可以参考以下链接, 里面包含不同的字符集合。

```
https://github.com/JinpengLI/deep_ocr/tree/master/python/deep_ocr/langs
```

下面的路径是指向哪些字体文件夹

```
/opt/deep_ocr/data/fonts/chinese_fonts
```

这样清楚一些?

**Comment by chibai** [comment]
@JinpengLI 
多谢指教，我想问的是，你是如何遍历所有汉字的？？我看你的教程只有字母没有汉字啊........给我贴点具体的代码。

假设我现在有身份证字体TTF文件，如何遍历得到这么多汉字的图片

输入时TTF文件，输出是图片
有木有具体函数，提示下

**Comment by chibai** [comment]
@JinpengLI
多谢了，我已经知道你的字库是复制粘贴出来的，不是什么黑魔法~~

我现在就想知道能指定TTF文件生成相应的字库图片吗
有没有具体函数说一下，我比较弱，问的问题也蠢

**Comment by chibai** [comment]
@JinpengLI
你的代码好多层次好复杂啊
请问TTF文件是哪个包读进去的，是PIL包吗？？
CV2和PIL包在我眼里不是同质的包吗，你用CV2做了什么PIL不能实现的功能吗？

**Comment by chibai** [comment]
@JinpengLI 
很清楚了，我现在想知道，如何让文字居中显示
因为在我的代码中，文字没法居中显示啊~！！真蛋疼
