### ISSUE TITLE
找到BUG了！！

### ISSUE THREAD

**Issue by chibai** [JinpengLI/deep_ocr#8]
PYTHON的BUG
㧟 䏝 㤘 䥽 䁖 䦃 㸆
这几个字无法通过PIL画出来，不信你试试
我平常不用PYTHON，这种BUG该往哪报啊？？
简单的测试代码

font = ImageFont.truetype("STXIHEI.TTF", 300)
img = Image.new("L", (300, 300), "black")
draw = ImageDraw.Draw(img)
ch = u'㸆'
draw.text((0, -75), ch, 255, font=font)
img.show()

你可以试试，哈哈蛤
把STXIHEI.TTF找出来，系统里就有，是华文细黑！！

**Comment by chibai** [comment]
大哥你是用什么模型训练的啊？？

**Comment by JinpengLI** [comment]
不好意思，放了一个长假（圣诞+新年），这个跟字体文件有关，字体文件不一定包含所有字，字体文件没有这个字就输出不了。。所以跟这个项目没有关系。。我关闭这个issue。。

> 大哥你是用什么模型训练的啊？？

就如README所说:
```
Deep Convolutional Network for Handwritten Chinese Character Recognition

http://cs231n.stanford.edu/reports/zyh_project.pdf
```
